# cd.yml 

name: CD

on:
  push:
    branches: [ "develop" ]

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: {s3버켓 이름}
  CODE_DEPLOY_APPLICATION_NAME: {codedeploy의 애플리케이션 이름}
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: {codedeploy의 배포그룹 이름}
  
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: 체크아웃 Github-Action
      uses: actions/checkout@v4

    - name: 자바 JDK set up
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Gradle set up
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: gradlew 권한 부여
      run: chmod +x ./gradlew
      working-directory: ./{gradlew가 위치한 경로} # 예시: ./cicd
      
    - name: Gradle 빌드
      run: ./gradlew clean build -x test
      working-directory: ./{gradle가 위치한 경로} # 예시:./cicd
  
    - name: AWS 인증 (IAM 사용자 Access key, Secret Key 사용)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Move appspec.yml to root (최상단으로 이동)
      run: mv {appspec.yml이 위치한폴더/appspec.yml} .  # 예시 cicd/appspec.yml

    - name: AWS S3 에 build 결과 업로드
      run: |
          aws deploy push \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --ignore-hidden-files \
            --s3-location s3://${{ env.S3_BUCKET_NAME }}/${{ github.sha }}.zip \
            --source . \
            --region ${{ env.AWS_REGION }}  # 리전 추가
      
    - name: S3 버킷 내 파일 CodeDeploy 실행
      run: |
          aws deploy create-deployment \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{ env.S3_BUCKET_NAME }},key=${{ github.sha }}.zip,bundleType=zip \
            --region ${{ env.AWS_REGION }}
