# ci.yml 

name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    
    - name: Github-Action 체크아웃
      uses: actions/checkout@v4
    
    - name: 자바 JDK set up
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Gradle set up
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: gradlew 권한 부여
      run: chmod +x {gradlew가 위치한폴더/gradlew} # 예시: cicd/gradlew

    - name: Gradle 빌드 (dev 프로파일 활성화)
      working-directory: ./{gradle가 위치한 경로} # 예시: ./cicd
      run: ./gradlew clean build -x test
      

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: 자바 JDK set up
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
